//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGES.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAM_Familias
    {
        public int IdFamilia { get; set; }
        public int Folio { get; set; }
        public int RUTUsuario { get; set; }
        public string NombreFamilia { get; set; }
        public string Direccion { get; set; }
        public string ReferenciaDir { get; set; }
        public int Telefono1 { get; set; }
        public Nullable<int> Telefono2 { get; set; }
        public int IdGestorFamiliar { get; set; }
        public bool EstadoApoLaboral { get; set; }
    
        public virtual GEN_GestoresFamiliares GEN_GestoresFamiliares { get; set; }
        public virtual GEN_Usuarios GEN_Usuarios { get; set; }
        public virtual INT_Integrantes INT_Integrantes { get; set; }
    }
}
