//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGES.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_GestoresFamiliares
    {
        public GEN_GestoresFamiliares()
        {
            this.FAM_Familias = new HashSet<FAM_Familias>();
        }
    
        public int IdGestorFamiliar { get; set; }
        public string Nombres { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public int Telefono { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<FAM_Familias> FAM_Familias { get; set; }
    }
}
