//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGES.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_Usuarios
    {
        public GEN_Usuarios()
        {
            this.FAM_Familias = new HashSet<FAM_Familias>();
        }
    
        public int RUT { get; set; }
        public string DV { get; set; }
        public string Nombres { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public Nullable<int> Fono { get; set; }
        public int Celular { get; set; }
        public string Email { get; set; }
        public string Imagen { get; set; }
        public int IdRol { get; set; }
        public string Clave { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<FAM_Familias> FAM_Familias { get; set; }
        public virtual GEN_Rol GEN_Rol { get; set; }
    }
}
