//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGES.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_Rol
    {
        public GEN_Rol()
        {
            this.GEN_Usuarios = new HashSet<GEN_Usuarios>();
        }
    
        public int IdRol { get; set; }
        public string Rol { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<GEN_Usuarios> GEN_Usuarios { get; set; }
    }
}
