//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGES.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NivelesEscolaridad
    {
        public INT_NivelesEscolaridad()
        {
            this.INT_Integrantes = new HashSet<INT_Integrantes>();
        }
    
        public int IdNivelEscolar { get; set; }
        public string NivelEscolar { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<INT_Integrantes> INT_Integrantes { get; set; }
    }
}
