//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGES.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_Integrantes
    {
        public INT_Integrantes()
        {
            this.FAM_Familias = new HashSet<FAM_Familias>();
        }
    
        public int RUT { get; set; }
        public string DV { get; set; }
        public string Nombres { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public int IdParentesco { get; set; }
        public bool Sexo { get; set; }
        public System.DateTime FechaNac { get; set; }
        public int IdEstadoCivil { get; set; }
        public int IdNivelEscolar { get; set; }
        public int IdOcupacion { get; set; }
        public string DescOcupacion { get; set; }
    
        public virtual GEN_EstadoCivil GEN_EstadoCivil { get; set; }
        public virtual GEN_Parentescos GEN_Parentescos { get; set; }
        public virtual INT_NivelesEscolaridad INT_NivelesEscolaridad { get; set; }
        public virtual INT_Ocupaciones INT_Ocupaciones { get; set; }
        public virtual ICollection<FAM_Familias> FAM_Familias { get; set; }
    }
}
