//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGES.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SisGENEntities : DbContext
    {
        public SisGENEntities()
            : base("name=SisGENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FAM_Familias> FAM_Familias { get; set; }
        public DbSet<GEN_EstadoCivil> GEN_EstadoCivil { get; set; }
        public DbSet<GEN_GestoresFamiliares> GEN_GestoresFamiliares { get; set; }
        public DbSet<GEN_Parentescos> GEN_Parentescos { get; set; }
        public DbSet<GEN_Rol> GEN_Rol { get; set; }
        public DbSet<GEN_Usuarios> GEN_Usuarios { get; set; }
        public DbSet<INT_Integrantes> INT_Integrantes { get; set; }
        public DbSet<INT_NivelesEscolaridad> INT_NivelesEscolaridad { get; set; }
        public DbSet<INT_Ocupaciones> INT_Ocupaciones { get; set; }
    }
}
